version: "3"

services:
  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 14G
        reservations:
          memory: 14G
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_ADDRESS=http://seq:5341
    ports:
      - "80:80"
      - "5341:5341"

volumes:
  seq-data:
