###
GRPC localhost:5280/TagToolBackendNew.TagService/InvokeOperation
Content-Type: application/json

{
  "itemId": "00000000-0000-0000-0000-000000000000",
  "operationArgs": "{\"newName\":\"test\"}",
  "operationName": "file:rename"
}

<> 2025-01-11T235236.OK.json
<> 2025-01-11T235147.OK.json
<> 2025-01-11T235106.OK.json
<> 2025-01-11T234846.OK.json

###
GRPC localhost:5280/TagToolBackendNew.TagService/TagItem
Content-Type: application/json

{
  "itemId": "01948887-cf42-74b7-867d-6f2683eb9f18",
  "tagId": 3
}

<> 2025-01-11T233858.OK.json

###
GRPC localhost:5280/TagToolBackendNew.TagService/SearchTags
Content-Type: application/json

{
  "searchType": "Fuzzy",
  "searchText": "t"
}

###
GRPC localhost:5280/TagToolBackendNew.TagService/CreateTag
Content-Type: application/json

{
  "text": "TestTag3"
}

###
GRPC localhost:5280/TagToolBackendNew.TagService/AddItem
Content-Type: application/json

{
  "itemType": "file",
  "itemArgs": "{\"path\":\"/home/tczyz/Documents/TagTool/TagToolPlayground/polisa-wypowiedzenie.jpeg\"}"
}

###
GRPC localhost:5280/TagToolBackendNew.TagService/GetOperations
Content-Type: application/json

### Get Invocable definitions
GRPC localhost:5280/TagToolBackendNew.InvocablesService/GetInvocablesDescriptions
Content-Type: application/json

### Create event-triggered job
GRPC localhost:5280/TagToolBackendNew.InvocablesService/CreateInvocable
Content-Type: application/json

{
  "invocable_id": "418B5746",
  "event_trigger": {},
  "args": "{\"CommonStoragePathString\":\"/home/tczyz/Documents/TagTool/CommonStorage\",\"Path\":\"/home/tczyz/Documents/TagTool/CommonStorage\",\"TagId\":1}"
}

### Create cron-triggered job
GRPC localhost:5280/TagToolBackendNew.InvocablesService/CreateInvocable
Content-Type: application/json

{
  "invocable_id": "FF0969B2",
  "cron_trigger": {
    "cron_expression": "* * * * *",
    "queryParams": [
      {
        "tag": {
          "id": 1
        },
        "state": "Include"
      }
    ]
  },
  "args": "{\"CommonStoragePathString\":\"null\",\"Path\":\"null\",\"TagId\":0}"
}

###
GRPC localhost:5280/TagToolBackendNew.InvocablesService/BroadcastEvent
Content-Type: application/json

{
}
